from . import help
from . import start
from . import info
from . import menu
from . import dasturlash
from . import pythonMenu
from . import tilKurslari
from . import productCallbacks
from . import echo